run_simulation:
  enabled: true
  save_data: true
load_simulation:
  enabled: false
  inpath: "runs/our_solar_system/3_bodies/euler_0t0_10tf_2dt/solved.pkl"
make_plots: true

N: 3
mf: 1
ic: "our_solar_system"
t0: 0 # Start time in years.
tf: 10 # End time in years.
dt: 2 # Step time in hours.
method:
  euler: true
  ec: false
  rk2: false
  rk4: false
  vv: false
  pv: false
  vefrl: false
  pefrl: false
plots:
  make_all: false
  total_system_energy: true
  kinetic_energy: true
  potential_energy: true
  trajectories:
    3d: true
    x: true
    y: true
    z: true
  phase_space:
    momentum:
      x: true
      y: true
      z: true
    kinetic_energy:
      x: true
      y: true
      z: true
    potential_energy:
      x: true
      y: true
      z: true
colors:
  red: "#ff0000"
  grey: "#8c8c94"
  pale_yellow: "#ffd56f"
  sea_blue: "#005e7b"
  reddish_brown: "#a06534"
  rifle_green: "#404436"
  magenta: "#7a26e7"
  pale_green: "#5CCE2A"
  black: "#000000"
  purple: "#4542f4"
ics:
  our_solar_system:
    m:
    - 1.989e+30 # Sun
    - 3.285e+23 # Mercury
    - 4.867e+24 # Venus
    - 5.972e+24 # Earth
    - 6.417e+23 # Mars
    - 1.898e+27 # Jupiter
    - 5.683e+26 # Saturn
    - 8.681e+25 # Uranus
    - 1.024e+26 # Neptune
    - 1.309e+22 # Pluto
    r0:
    - [1.0e+11, 3.0e+11, 2.0e+11] # Sun
    - [6.0e+11, -5.0e+11, 4.0e+11] # Mercury
    - [7.0e+11, 8.0e+11, -7.0e+11] # Venus
    - [8.0e+11, 6.0e+11, -2.0e+11] # Earth
    - [8.8e+11, 9.8e+11, -6.8e+11] # Mars
    - [9.8e+11, 3.8e+11, -7.8e+11] # Jupiter
    - [-3.8e+11, 1.8e+11, 4.8e+11] # Saturn
    - [7.8e+11, -2.2e+11, 1.8e+11] # Uranus
    - [6.8e+11, -4.1e+11, 3.8e+11] # Neptune
    - [5.8e+11, -9.3e+11, 5.8e+11] # Pluto
    v0:
    - [0.0, 0.0, 0.0] # Sun
    - [7.0e+3, 0.5e+3, 2.0e+3] # Mercury
    - [-4.0e+3, -0.5e+3, -3.0e+3] # Venus
    - [7.0e+3, 0.5e+3, 2.0e+3] # Earth
    - [4.8e+3, 1.3e+3, 4.8e+3] # Mars
    - [1.8e+3, 1.2e+3, -5.8e+3] # Jupiter
    - [2.8e+3, 11.3e+3, 1.4e+3] # Saturn
    - [3.8e+3, 10.3e+3, 2.4e+3] # Uranus
    - [4.8e+3, 9.3e+3, -1.4e+3] # Neptune
    - [5.8e+3, 0.3e+3, -2.4e+3] # Pluto

  # This set of ICs is more like stars orbiting each other. The resulting orbital
  # trajectories are far less stable than those resulting from `our_solar_system`.
  four_stars:
    m:
    - 1e30 # 0
    - 2e30 # 1
    - 3e30 # 2
    - 2.5e30 # 3
    r0:
    - [1.0e+11, 3.0e+11, 2.0e+11] # 0
    - [6.0e+11, -5.0e+11, 4.0e+11] # 1
    - [7.0e+11, 8.0e+11, -7.0e+11] # 2
    - [8.0e+11, 6.0e+11, -2.0e+11] # 3
    v0:
    - [-2.0e+3, 0.5e+3, 5.0e+3] # 0
    - [7.0e+3, 0.5e+3, 2.0e+3] # 1
    - [-4.0e+3, -0.5e+3, -3.0e+3] # 2
    - [7.0e+3, 0.5e+3, 2.0e+3] # 3

  # This set of ICs provides a test case where there is a central massive body, and
  # then 6 symmetrically-arranged bodies around it, all starting with zero velocity.
  symmetry:
    m:
    - 2e+30 # Center
    - 3.285e+23
    - 3.285e+23
    - 3.285e+23
    - 3.285e+23
    - 3.285e+23
    - 3.285e+23
    r0:
    - [0.0e+11, 0.0e+11, 0.0e+11] # Center
    - [1.0e+11, 0.0e+11, 0.0e+11]
    - [0.0e+11, 1.0e+11, 0.0e+11]
    - [0.0e+11, 0.0e+11, 1.0e+11]
    - [-1.0e+11, 0.0e+11, 0.0e+11]
    - [0.0e+11, -1.0e+11, 0.0e+11]
    - [0.0e+11, 0.0e+11, -1.0e+11]
    v0:
    - [0.0, 0.0, 0.0]
    - [0.0, 0.0, 0.0]
    - [0.0, 0.0, 0.0]
    - [0.0, 0.0, 0.0]
    - [0.0, 0.0, 0.0]
    - [0.0, 0.0, 0.0]
    - [0.0, 0.0, 0.0]
