n: 4
ic: "our_solar_system"
t0: 0 # Start time in years.
tf: 20 # End time in years.
dt: 2 # Step time in hours.
G: 6.67e-11 # Universal gravitational constant in units of m^3/kg*s^2.
method:
  euler: false
  ec: false
  rk2: false
  rk4: false
  vv: false
  pv: false
  vefrl: false
  pefrl: false
figs:
  gen_all: false
  trajectories:
    3d: false
    x: false
    y: false
    z: false
  phase_space:
    momentum:
      x: false
      y: false
      z: false
    kinetic_energy:
      system: false
      each: false
      x: false
      y: false
      z: false
colors:
  red: "#ff0000"
  grey: "#8c8c94"
  pale_yellow: "#ffd56f"
  sea_blue: "#005e7b"
  reddish_brown: "#a06534"
  rifle_green: "#404436"
  magenta: "#7a26e7"
  pale_green: "#5CCE2A"
  black: "#000000"
  purple: "#4542f4"
ics:
  our_solar_system:
    m:
    - 1.989e30 # Sun
    - 3.285e23 # Mercury
    - 4.867e24 # Venus
    - 5.972e24 # Earth
    - 6.417e23 # Mars
    - 1.898e27 # Jupiter
    - 5.683e26 # Saturn
    - 8.681e25 # Uranus
    - 1.024e26 # Neptune
    - 1.309e22 # Pluto

    r0:
    - [1.0e11, 3.0e11, 2.0e11] # Sun
    - [6.0e11, -5.0e11, 4.0e11] # Mercury
    - [7.0e11, 8.0e11, -7.0e11] # Venus
    - [8.0e11, 6.0e11, -2.0e11] # Earth
    - [8.8e11, 9.8e11, -6.8e11] # Mars
    - [9.8e11, 3.8e11, -7.8e11] # Jupiter
    - [-3.8e11, 1.8e11, 4.8e11] # Saturn
    - [7.8e11, -2.2e11, 1.8e11] # Uranus
    - [6.8e11, -4.1e11, 3.8e11] # Neptune
    - [5.8e11, -9.3e11, 5.8e11] # Pluto
    v0:
    - [0.0, 0.0, 0.0] # Sun
    - [7.0e3, 0.5e3, 2.0e3] # Mercury
    - [-4.0e3, -0.5e3, -3.0e3] # Venus
    - [7.0e3, 0.5e3, 2.0e3] # Earth
    - [4.8e3, 1.3e3, 4.8e3] # Mars
    - [1.8e3, 1.2e3, -5.8e3] # Jupiter
    - [2.8e3, 11.3e3, 1.4e3] # Saturn
    - [3.8e3, 10.3e3, 2.4e3] # Uranus
    - [4.8e3, 9.3e3, -1.4e3] # Neptune
    - [5.8e3, 0.3e3, -2.4e3] # Pluto

  # This set of ICs is more like stars orbiting each other. The resulting orbital
  # trajectories are far less stable than those resulting from `our_solar_system`.
  four_stars:
    m:
    - 1e30 # 0
    - 2e30 # 1
    - 3e30 # 2
    - 2.5e30 # 3
    r0:
    - [1.0e11, 3.0e11, 2.0e11] # 0
    - [6.0e11, -5.0e11, 4.0e11] # 1
    - [7.0e11, 8.0e11, -7.0e11] # 2
    - [8.0e11, 6.0e11, -2.0e11] # 3
    v0:
    - [-2.0e3, 0.5e3, 5.0e3] # 0
    - [7.0e3, 0.5e3, 2.0e3] # 1
    - [-4.0e3, -0.5e3, -3.0e3] # 2
    - [7.0e3, 0.5e3, 2.0e3] # 3

  # This set of ICs provides a test case where there is a central massive body, and
  # then 6 symmetrically-arranged bodies around it, all starting with zero velocity.
  symmetry:
    m:
    - 2e30 # Center
    - 3.285e23
    - 3.285e23
    - 3.285e23
    - 3.285e23
    - 3.285e23
    - 3.285e23
    r0:
    - [0.0e11, 0.0e11, 0.0e11] # Center
    - [1.0e11, 0.0e11, 0.0e11]
    - [0.0e11, 1.0e11, 0.0e11]
    - [0.0e11, 0.0e11, 1.0e11]
    - [-1.0e11, 0.0e11, 0.0e11]
    - [0.0e11, -1.0e11, 0.0e11]
    - [0.0e11, 0.0e11, -1.0e11]
    v0:
    - [0.0, 0.0, 0.0]
    - [0.0, 0.0, 0.0]
    - [0.0, 0.0, 0.0]
    - [0.0, 0.0, 0.0]
    - [0.0, 0.0, 0.0]
    - [0.0, 0.0, 0.0]
    - [0.0, 0.0, 0.0]
