masses:
- 1.989e30 # mass of the sun
- 3.285e23 # mass of Mercury
- 4.867e24 # mass of Venus
- 5.972e24 # mass of Earth
- 6.417e23 # mass of Mars
- 1.898e27 # mass of Jupiter
- 5.683e26 # mass of Saturn
- 8.681e25 # mass of Uranus
- 1.024e26 # mass of Neptune
- 1.309e22 # mass of Pluto
